site_name: Intro to Docker
nav:
    - Home: index.md
    - About: about.md
    - 'Working with Containers':
      - 'What is a Container?': working-with-containers/what-is-a-container.md
      - 'Basic Docker Commands': working-with-containers/basic-docker-commands.md
      - 'Pulling and Running Containers': working-with-containers/pulling-and-running-containers.md
      - 'Working with Images': working-with-containers/working-with-images.md
      - 'Container Lifecycle': working-with-containers/container-lifecycle.md
      - 'List of Common Docker Commands': working-with-containers/list-of-commands.md
    - 'Swarm Mode and Microservices':
      - 'Swarm Mode Theory': swarm-mode-and-microservices/swarm-mode-theory.md
      - 'Configuring Swarm Mode': swarm-mode-and-microservices/configuring-swarm-mode.md
      - 'Services': swarm-mode-and-microservices/services.md
      - 'Scaling Services': swarm-mode-and-microservices/scaling-services.md
      - 'Rolling Updates': swarm-mode-and-microservices/rolling-updates.md
theme: material